# Generated by Django 5.2.14 on 2026-06-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_content_comment_body_comment_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_publish', 'Can publish articles'), ('can_feature', 'Can feature articles')]},
        ),
    ]
