# Generated by Django 5.2.15 on 2026-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auto_translate',
            field=models.BooleanField(default=True, help_text='ترجمة تلقائية للإنجليزية (Auto-translate to English)'),
        ),
    ]
