# Generated by Django 5.2.15 on 2026-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='أقسام فرعية إضافية (اختياري)', related_name='additional_articles', to='news.category'),
        ),
    ]
