# Generated by Django 5.2.15 on 2026-06-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_additional_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_breaking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('review', 'مراجعة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', max_length=20),
        ),
    ]
