# Generated by Django 5.2.15 on 2026-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_is_breaking_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('review', 'مراجعة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='published', max_length=20),
        ),
    ]
