# Generated by Django 5.2.15 on 2026-06-25 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
