# Generated by Django 5.2.14 on 2026-07-07 06:23

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_article_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, help_text='Gemini API Key. If empty, uses environment variable.', max_length=255, null=True)),
                ('articles_per_day', models.PositiveIntegerField(default=3, help_text='Number of articles to publish daily.')),
                ('max_words', models.PositiveIntegerField(default=500, help_text='Max word count per article.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle AI news fetching on or off.')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Global Settings',
                'verbose_name_plural': 'AI Global Settings',
            },
        ),
        migrations.CreateModel(
            name='AISource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموقع المصدر')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='رابط التغذية RSS أو الموقع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('language', models.CharField(choices=[('ar', 'عربي (Arabic)'), ('en', 'إنجليزي/عالمي (English/Global)'), ('both', 'مختلط (Mixed)')], default='ar', max_length=10, verbose_name='لغة المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sources', to='news.category', verbose_name='القسم المستهدف')),
            ],
            options={
                'verbose_name': 'AI News Source',
                'verbose_name_plural': 'AI News Sources',
            },
        ),
        migrations.CreateModel(
            name='AIImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='رابط الخبر الأصلي')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الخبر')),
                ('status', models.CharField(choices=[('success', 'نجاح (Success)'), ('failed', 'فشل (Failed)')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='news.article', verbose_name='الخبر المنشور')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='news.aisource', verbose_name='المصدر')),
            ],
            options={
                'verbose_name': 'AI Import Log',
                'verbose_name_plural': 'AI Import Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
