# Generated by Django 5.2.14 on 2026-07-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_aisettings_aisource_aiimportlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الموقع')),
                ('url', models.URLField(max_length=500, verbose_name='رابط الموقع (WordPress URL)')),
                ('username', models.CharField(max_length=150, verbose_name='اسم المستخدم في ووردبريس')),
                ('application_password', models.CharField(max_length=255, verbose_name='كلمة مرور التطبيق (Application Password)')),
                ('daily_limit', models.PositiveIntegerField(default=3, verbose_name='الحد الأقصى للنشر اليومي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category_mapping', models.TextField(default='{}', help_text='خريطة الأقسام بتنسيق JSON، مثال: {"اسم القسم المحلي": معرف_القسم_في_ووردبريس}', verbose_name='خريطة الأقسام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sources', models.ManyToManyField(related_name='wp_sites', to='news.aisource', verbose_name='مصادر الأخبار المرتبطة')),
            ],
            options={
                'verbose_name': 'WordPress Site',
                'verbose_name_plural': 'WordPress Sites',
            },
        ),
    ]
