# Generated by Django 5.2.14 on 2026-07-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_wordpresssite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ai_settings', to='news.category', verbose_name='الأقسام المتاحة للنشر'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='default_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_settings', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب الافتراضي للأخبار'),
        ),
    ]
