# Generated by Django 5.2.14 on 2026-07-07 07:16

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_aisettings_categories_aisettings_default_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisource',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sources_direct', to='news.wordpresssite', verbose_name='الموقع المستهدف'),
        ),
        migrations.AlterField(
            model_name='aisource',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_sources', to='news.category', verbose_name='القسم المستهدف'),
        ),
    ]
