# Generated by Django 5.2.14 on 2026-07-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_aisource_site_alter_aisource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpresssite',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='wp_sites', to='news.aisource', verbose_name='مصادر الأخبار المرتبطة'),
        ),
    ]
