# Generated by Django 5.2.14 on 2026-07-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_wordpresssite_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisource',
            name='site',
        ),
    ]
