# Generated by Django 5.2.14 on 2026-07-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_remove_aisource_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisource',
            name='category',
        ),
    ]
