# Generated by Django 5.2.14 on 2026-07-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_remove_aisource_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auto_translate',
            field=models.BooleanField(default=False, help_text='ترجمة تلقائية للإنجليزية (Auto-translate to English)'),
        ),
    ]
