# Generated by Django 5.2.14 on 2026-07-07 09:48

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_article_auto_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='api_token',
            field=models.CharField(default=news.models.generate_api_token, help_text='مفتاح الأمان للربط الآمن بالووردبريس (Django API Token).', max_length=255, unique=True),
        ),
    ]
