# Generated by Django 5.2.14 on 2026-07-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_aisettings_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportlog',
            name='published_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الخبر المنشور'),
        ),
        migrations.AddField(
            model_name='aiimportlog',
            name='wp_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='news.wordpresssite', verbose_name='الموقع المستهدف'),
        ),
    ]
