# Generated by Django 5.2.14 on 2026-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_aiimportlog_published_url_aiimportlog_wp_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='telegram_allowed_chats',
            field=models.TextField(blank=True, help_text='معرفات محادثات تليجرام المسموحة، مفصولة بفاصلة (مثال: 1234567, 9876543).', null=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='رمز توكن بوت تليجرام (Telegram Bot Token) للتحكم بالنظام.', max_length=255, null=True),
        ),
    ]
