# Generated by Django 5.2.14 on 2026-07-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_aisettings_telegram_allowed_chats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='local_sources',
            field=models.ManyToManyField(blank=True, help_text='إذا تركت هذا الحقل فارغاً سيستخدم النظام جميع المصادر النشطة للنشر المحلي.', related_name='local_ai_settings', to='news.aisource', verbose_name='مصادر الأخبار المغذية لموقع المغرب العربي'),
        ),
    ]
