# Generated by Django 5.2.14 on 2026-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_aisettings_local_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='publish_to_main_site',
            field=models.BooleanField(default=True, help_text='تفعيل أو تعطيل نشر الأخبار المولدة على الموقع الرئيسي.', verbose_name='النشر على الموقع الأساسي'),
        ),
    ]
