# Generated by Django 5.2.14 on 2026-07-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_aisettings_publish_to_main_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiimportlog',
            name='published_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='رابط الخبر المنشور'),
        ),
        migrations.AlterField(
            model_name='aiimportlog',
            name='source_url',
            field=models.URLField(max_length=1000, verbose_name='رابط الخبر الأصلي'),
        ),
        migrations.AlterField(
            model_name='aisource',
            name='url',
            field=models.URLField(max_length=1000, unique=True, verbose_name='رابط التغذية RSS أو الموقع'),
        ),
        migrations.AlterField(
            model_name='wordpresssite',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='رابط الموقع (WordPress URL)'),
        ),
    ]
