# Generated by Django 5.2.14 on 2026-07-16 15:24

from decimal import Decimal

from django.db import migrations, models


def backfill_estimated_cost(apps, schema_editor):
    AIImportLog = apps.get_model('news', 'AIImportLog')
    for log in AIImportLog.objects.select_related('article').iterator():
        if log.status == 'failed' and log.error_message and "لم يستجب الـ API" in log.error_message:
            cost = Decimal('0')
        else:
            input_tokens = 1500
            if log.article_id:
                article = log.article
                text = f"{article.title or ''} {article.excerpt or ''} {article.body or ''}"
                word_count = len(text.split())
                output_tokens = int(word_count * 2.2)
            elif log.status == 'success':
                output_tokens = 800
            else:
                output_tokens = 400
            input_cost = (input_tokens / 1000000.0) * 0.30
            output_cost = (output_tokens / 1000000.0) * 2.50
            cost = Decimal(str(input_cost + output_cost))
        log.estimated_cost = cost
        log.save(update_fields=['estimated_cost'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_alter_aiimportlog_published_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportlog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=10, verbose_name='التكلفة التقديرية (USD)'),
        ),
        migrations.RunPython(backfill_estimated_cost, noop),
    ]
