# Generated by Django 5.2.14 on 2026-07-16 15:30

import core.fields
from django.db import migrations


def encrypt_existing_plaintext_values(apps, schema_editor):
    """
    Encrypts values that were written while these columns were plain
    CharFields. Uses raw SQL (not the ORM) so it reads the still-plaintext
    bytes directly, before the AlterField below switches field conversion on.
    """
    from core.fields import _get_fernet

    fernet = _get_fernet()

    def encrypt(value):
        if not value:
            return value
        return fernet.encrypt(value.encode()).decode()

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, gemini_api_key, telegram_bot_token FROM news_aisettings")
        rows = cursor.fetchall()
        for row_id, gemini_api_key, telegram_bot_token in rows:
            cursor.execute(
                "UPDATE news_aisettings SET gemini_api_key = %s, telegram_bot_token = %s WHERE id = %s",
                [encrypt(gemini_api_key), encrypt(telegram_bot_token), row_id],
            )

        cursor.execute("SELECT id, application_password FROM news_wordpresssite")
        rows = cursor.fetchall()
        for row_id, application_password in rows:
            cursor.execute(
                "UPDATE news_wordpresssite SET application_password = %s WHERE id = %s",
                [encrypt(application_password), row_id],
            )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_aiimportlog_estimated_cost'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_plaintext_values, noop),
        migrations.AlterField(
            model_name='aisettings',
            name='gemini_api_key',
            field=core.fields.EncryptedCharField(blank=True, help_text='Gemini API Key. If empty, uses environment variable.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='telegram_bot_token',
            field=core.fields.EncryptedCharField(blank=True, help_text='رمز توكن بوت تليجرام (Telegram Bot Token) للتحكم بالنظام.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wordpresssite',
            name='application_password',
            field=core.fields.EncryptedCharField(max_length=500, verbose_name='كلمة مرور التطبيق (Application Password)'),
        ),
    ]
