# Generated by Django 5.2.14 on 2026-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_alter_aisettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='heading_color',
            field=models.CharField(default='#0066cc', help_text='كود اللون السداسي عشري (Hex)، مثال: #0066cc', max_length=7, verbose_name='لون العناوين الفرعية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='use_rich_formatting',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُقسَّم الخبر إلى عناوين فرعية H2/H3 ملوّنة بدلاً من فقرات فقط، مع إضافة وسوم (Tags) تلقائية لتحسين توافق السيو (Yoast).', verbose_name='تنسيق غني بعناوين فرعية ملوّنة (SEO)'),
        ),
    ]
