# Generated by Django 5.2.14 on 2026-07-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_wordpresssite_heading_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='wp_author_id',
            field=models.PositiveIntegerField(blank=True, help_text='معرّف (ID) المستخدم في ووردبريس الذي سيُنسب إليه المقال المنشور. اتركه فارغاً لينشر باسم المستخدم المستخدم في المصادقة (username أعلاه).', null=True, verbose_name='معرف الكاتب في ووردبريس (Author ID)'),
        ),
    ]
