# Generated by Django 5.2.14 on 2026-07-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_wordpresssite_wp_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='use_internal_links',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يحاول النظام تضمين رابط داخلي أو رابطين ضمن نص الخبر يشيران إلى مقالات حديثة أخرى منشورة على هذا الموقع نفسه.', verbose_name='إضافة روابط داخلية تلقائية (SEO)'),
        ),
    ]
