# Generated by Django 5.2.14 on 2026-07-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_wordpresssite_use_internal_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_gold_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام في كل دورة توليد مقالاً جديداً بسعر الذهب اللحظي (عيار 24، 21، 18) بالجنيه المصري لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الذهب الحية'),
        ),
    ]
