# Generated by Django 5.2.14 on 2026-07-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_wordpresssite_generate_gold_price_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='last_gold_price_24k_egp',
            field=models.FloatField(blank=True, help_text='يُستخدم داخلياً لمقارنة سعر الذهب بالتحديث السابق.', null=True, verbose_name='آخر سعر مسجَّل لجرام الذهب عيار 24 (جنيه)'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_gold_price_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تسجيل لسعر الذهب'),
        ),
    ]
