# Generated by Django 5.2.14 on 2026-07-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_aisettings_last_gold_price_24k_egp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='site_tags',
            field=models.TextField(blank=True, default='', help_text='وسوم ثابتة (افصل بينها بفاصلة) تُضاف تلقائياً لكل خبر يُنشر على هذا الموقع، مثال: بانكرز توداي, موقع بانكرز توداي الاخباري', verbose_name='وسوم ثابتة لهذا الموقع'),
        ),
    ]
