# Generated by Django 5.2.14 on 2026-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_wordpresssite_site_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='use_explainer_style',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يقرر الذكاء الاصطناعي تلقائياً استخدام أسلوب شرح بعناوين على شكل أسئلة (لماذا؟ هل؟ كيف؟) للأخبار الاقتصادية/التنظيمية (رسوم، ضرائب، قرارات) التي تحتاج تفصيلاً، بدلاً من الخبر القصير المعتاد.', verbose_name='أسلوب تفسيري (Explainer) عند الحاجة'),
        ),
    ]
