# Generated by Django 5.2.14 on 2026-07-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_wordpresssite_use_explainer_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='last_dollar_price_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تسجيل لسعر الدولار'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_dollar_price_egp',
            field=models.FloatField(blank=True, help_text='يُستخدم داخلياً لمقارنة سعر الدولار بالتحديث السابق.', null=True, verbose_name='آخر سعر صرف مسجَّل للدولار (جنيه)'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_silver_price_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر تسجيل لسعر الفضة'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_silver_price_egp',
            field=models.FloatField(blank=True, help_text='يُستخدم داخلياً لمقارنة سعر الفضة بالتحديث السابق.', null=True, verbose_name='آخر سعر مسجَّل لجرام الفضة (جنيه)'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_dollar_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام في كل دورة توليد مقالاً جديداً بسعر صرف الدولار اللحظي مقابل الجنيه المصري لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الدولار الحية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_silver_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام في كل دورة توليد مقالاً جديداً بسعر الفضة اللحظي بالجنيه المصري لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الفضة الحية'),
        ),
    ]
