# Generated by Django 5.2.14 on 2026-07-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_aisettings_last_dollar_price_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='last_cement_price_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لسعر الإسمنت'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_fish_price_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لسعر السمك'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_iron_price_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لسعر الحديد'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_poultry_price_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لسعر الدواجن'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='last_vegetable_price_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لأسعار الخضار'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_cement_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بسعر الأسمنت الرمادي الرسمي لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الإسمنت اليومية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_fish_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بسعر السمك الرسمي لهذا الموقع فقط.', verbose_name='توليد مقالات سعر السمك اليومية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_iron_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بسعر حديد عز الرسمي (بيانات مركز معلومات مجلس الوزراء) لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الحديد اليومية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_poultry_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بسعر الدواجن الطازجة الرسمي لهذا الموقع فقط.', verbose_name='توليد مقالات سعر الدواجن اليومية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_vegetable_price_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بأسعار سلة خضار أساسية (طماطم، بطاطس، بصل) الرسمية لهذا الموقع فقط.', verbose_name='توليد مقالات أسعار الخضار اليومية'),
        ),
    ]
