# Generated by Django 5.2.14 on 2026-07-17 08:30

from django.conf import settings
from django.db import migrations, models


def copy_old_authors_forward(apps, schema_editor):
    AISettings = apps.get_model('news', 'AISettings')
    for settings_obj in AISettings.objects.all():
        if settings_obj.default_author_id:
            settings_obj.default_authors.add(settings_obj.default_author_id)

    WordPressSite = apps.get_model('news', 'WordPressSite')
    for site in WordPressSite.objects.exclude(wp_author_id__isnull=True):
        site.wp_author_ids = str(site.wp_author_id)
        site.save(update_fields=['wp_author_ids'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_aisettings_last_cement_price_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='default_authors',
            field=models.ManyToManyField(blank=True, help_text='عند اختيار أكثر من كاتب، يُنوَّع تلقائياً بينهم عشوائياً لكل خبر جديد. اتركه فارغاً لاستخدام حساب النظام الآلي.', related_name='ai_settings_authors', to=settings.AUTH_USER_MODEL, verbose_name='الكتّاب الافتراضيون للأخبار'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='wp_author_ids',
            field=models.TextField(blank=True, default='', help_text='معرّفات (IDs) مستخدمي ووردبريس الذين سيُنسب إليهم المقال، مفصولة بفاصلة. عند وجود أكثر من واحد يُختار أحدهم عشوائياً لكل مقال. اتركه فارغاً لينشر باسم مستخدم المصادقة (username أعلاه).', verbose_name='معرّفات الكتّاب في ووردبريس (Author IDs)'),
        ),
        migrations.RunPython(copy_old_authors_forward, noop),
        migrations.RemoveField(
            model_name='aisettings',
            name='default_author',
        ),
        migrations.RemoveField(
            model_name='wordpresssite',
            name='wp_author_id',
        ),
    ]
