# Generated by Django 5.2.14 on 2026-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_remove_aisettings_default_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='articles_per_run',
            field=models.PositiveIntegerField(default=1, help_text='أقصى عدد أخبار تُنشر لهذا الموقع في كل مرة تعمل فيها الدورة (يدوياً أو تلقائياً كل 4 ساعات)، بالإضافة إلى الحد الأقصى اليومي الإجمالي أعلاه.', verbose_name='عدد المقالات لكل تشغيل'),
        ),
    ]
