# Generated by Django 5.2.14 on 2026-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_wordpresssite_articles_per_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='last_arab_currencies_at',
            field=models.DateTimeField(blank=True, help_text='يُستخدم داخلياً لتقييد النشر لمرة واحدة يومياً.', null=True, verbose_name='وقت آخر نشر لأسعار العملات العربية'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='generate_arab_currencies_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بأسعار صرف الريال السعودي والدينار الكويتي والدرهم الإماراتي الرسمية مقابل الجنيه المصري لهذا الموقع فقط.', verbose_name='توليد مقالات أسعار العملات العربية اليومية'),
        ),
    ]
