# Generated by Django 5.2.14 on 2026-07-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_aisettings_last_arab_currencies_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpresssite',
            name='category_mapping',
            field=models.TextField(default='{}', help_text='خريطة الأقسام بتنسيق JSON. رقم واحد يُستخدم كقسم أساسي: {"اقتصاد": 5}. أو قسم أساسي وأقسام فرعية معاً: {"اقتصاد": {"primary": 5, "secondary": [12, 20]}}', verbose_name='خريطة الأقسام'),
        ),
    ]
