# Generated by Django 5.2.14 on 2026-07-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_alter_wordpresssite_category_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.TimeField(verbose_name='وقت الفترة (بتوقيت القاهرة)')),
                ('content_types', models.TextField(help_text='مفصولة بفاصلة، مثال: iron,vegetable', verbose_name='أنواع المحتوى')),
                ('regular_news_count', models.PositiveIntegerField(default=1, help_text='يُستخدم فقط إذا كانت "أخبار عامة" ضمن أنواع المحتوى المختارة أعلاه.', verbose_name='عدد الأخبار العامة في هذه الفترة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('last_run_date', models.DateField(blank=True, help_text='يُستخدم داخلياً لضمان تنفيذ هذه الفترة مرة واحدة فقط في يومها.', null=True, verbose_name='تاريخ آخر تنفيذ')),
                ('wp_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='news.wordpresssite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'فترة نشر مجدولة',
                'verbose_name_plural': 'فترات النشر المجدولة',
                'ordering': ['time_of_day'],
            },
        ),
    ]
