# Generated by Django 5.2.14 on 2026-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_wordpressscheduleslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordpressscheduleslot',
            name='last_run_date',
        ),
        migrations.AddField(
            model_name='wordpressscheduleslot',
            name='last_run_log',
            field=models.TextField(blank=True, default='{}', help_text='يُستخدم داخلياً لضمان تنفيذ كل نوع محتوى في هذه الفترة مرة واحدة فقط في يومه، بشكل مستقل عن باقي الأنواع في نفس الفترة.', verbose_name='سجل آخر تنفيذ لكل نوع'),
        ),
    ]
