# Generated by Django 5.2.14 on 2026-07-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_remove_wordpressscheduleslot_last_run_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordpresssite',
            name='generate_arab_currencies_articles',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُنشئ النظام مرة واحدة يومياً مقالاً بأسعار صرف الريال السعودي والدينار الكويتي والدرهم الإماراتي، بالإضافة لليورو والجنيه الاسترليني والفرنك السويسري، الرسمية مقابل الجنيه المصري لهذا الموقع فقط.', verbose_name='توليد مقالات أسعار العملات العربية والأجنبية اليومية'),
        ),
    ]
