# Generated by Django 5.2.15 on 2026-07-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_alter_wordpresssite_generate_arab_currencies_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordPressSiteGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجموعة')),
                ('is_active', models.BooleanField(default=True, help_text='عند التعطيل، تُعامل كل المواقع الأعضاء كمواقع مستقلة كالمعتاد.', verbose_name='نشطة (تفعيل الدمج)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مجموعة دمج مواقع',
                'verbose_name_plural': 'مجموعات دمج المواقع',
            },
        ),
        migrations.AddField(
            model_name='aiimportlog',
            name='input_tokens',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='توكنات الإدخال الفعلية'),
        ),
        migrations.AddField(
            model_name='aiimportlog',
            name='output_tokens',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='توكنات الإخراج الفعلية'),
        ),
        migrations.AlterField(
            model_name='aiimportlog',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=10, verbose_name='التكلفة الفعلية (USD)'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='merge_group',
            field=models.ForeignKey(blank=True, help_text='إذا انضم موقعان أو أكثر من نفس المجموعة النشطة لنفس الخبر، يُولَّد الخبر مرة واحدة (Master) ثم تُعاد صياغته بشكل أخف وأرخص لباقي أعضاء المجموعة بدلاً من توليد كامل ومستقل لكل موقع، لتقليل التكلفة. اتركه فارغاً ليبقى الموقع مستقلاً بالكامل بأسلوبه الخاص.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='news.wordpresssitegroup', verbose_name='مجموعة الدمج'),
        ),
    ]
