# Generated by Django 5.2.14 on 2026-07-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_wordpresssitegroup_aiimportlog_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image_alt',
            field=models.CharField(blank=True, default='', help_text='وصف احترافي لمحتوى الصورة نفسها لأغراض السيو وإمكانية الوصول - وليس تكراراً لعنوان الخبر. يُترك فارغاً لاستخدام العنوان كبديل احتياطي.', max_length=300, verbose_name='النص البديل للصورة (Alt Text)'),
        ),
    ]
