# Generated by Django 5.2.15 on 2026-07-19 17:05

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_article_cover_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordpresssite',
            name='facebook_access_token',
            field=core.fields.EncryptedCharField(blank=True, help_text='توكن وصول دائم (Long-Lived Page Access Token) يُنشأ يدوياً من أدوات مطوري فيسبوك لهذه الصفحة تحديداً.', max_length=1000, null=True, verbose_name='توكن وصول صفحة فيسبوك (Page Access Token)'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='facebook_page_id',
            field=models.CharField(blank=True, default='', help_text='اتركه فارغاً لتعطيل النشر التلقائي على فيسبوك مع إبقاء توليد الصورة فقط.', max_length=100, verbose_name='معرّف صفحة فيسبوك (Page ID)'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='social_image_enabled',
            field=models.BooleanField(default=False, help_text='عند التفعيل، يُولَّد تصميم صورة تلقائياً (صورة الخبر + عنوان + لوجو الموقع) عند نشر كل خبر جديد لهذا الموقع.', verbose_name='تفعيل توليد صور السوشال ميديا'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='social_logo',
            field=models.ImageField(blank=True, help_text='يُفضَّل صورة PNG بخلفية شفافة.', null=True, upload_to='site_logos/', verbose_name='لوجو الموقع'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='social_primary_color',
            field=models.CharField(default='#0d9488', help_text='كود اللون السداسي عشري (Hex)، مثال: #0d9488', max_length=7, verbose_name='اللون الأساسي للتصميم'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='social_secondary_color',
            field=models.CharField(default='#0f172a', help_text='كود اللون السداسي عشري (Hex)، مثال: #0f172a', max_length=7, verbose_name='اللون الثانوي للتصميم'),
        ),
        migrations.AddField(
            model_name='wordpresssite',
            name='social_template',
            field=models.CharField(choices=[('bottom_banner', 'شريط سفلي (صورة كاملة + شريط عنوان أسفل)'), ('boxed_card', 'بطاقة مؤطرة (صورة مع إطار وصندوق عنوان)'), ('split_block', 'تقسيم علوي/سفلي (صورة أعلى وكتلة لون بالعنوان أسفل)')], default='bottom_banner', max_length=20, verbose_name='قالب تصميم الصورة'),
        ),
        migrations.CreateModel(
            name='SocialSharePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان الخبر (وقت التوليد)')),
                ('template_used', models.CharField(choices=[('bottom_banner', 'شريط سفلي (صورة كاملة + شريط عنوان أسفل)'), ('boxed_card', 'بطاقة مؤطرة (صورة مع إطار وصندوق عنوان)'), ('split_block', 'تقسيم علوي/سفلي (صورة أعلى وكتلة لون بالعنوان أسفل)')], max_length=20, verbose_name='القالب المستخدم')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='social_shares/%Y/%m/', verbose_name='الصورة المولَّدة')),
                ('status', models.CharField(choices=[('generated', 'تم توليد الصورة'), ('posted', 'نُشرت على فيسبوك'), ('failed', 'فشل')], default='generated', max_length=20, verbose_name='الحالة')),
                ('facebook_post_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف منشور فيسبوك')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت النشر على فيسبوك')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='news.article', verbose_name='الخبر')),
                ('wp_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_posts', to='news.wordpresssite', verbose_name='الموقع')),
            ],
            options={
                'verbose_name': 'صورة سوشال ميديا',
                'verbose_name_plural': 'صور السوشال ميديا',
                'ordering': ['-created_at'],
            },
        ),
    ]
