# Generated by Django 5.2.14 on 2026-07-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_wordpresssite_facebook_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportlog',
            name='focus_keyword',
            field=models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='الكلمة المفتاحية'),
        ),
        migrations.AddField(
            model_name='aiimportlog',
            name='tag_names',
            field=models.TextField(blank=True, default='', editable=False, verbose_name='الوسوم (مفصولة بفاصلة)'),
        ),
        migrations.AddField(
            model_name='aiimportlog',
            name='wp_category_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='معرّف القسم في ووردبريس'),
        ),
    ]
