# Generated by Django 5.2.14 on 2026-07-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0046_aiimportlog_focus_keyword_aiimportlog_tag_names_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimportlog',
            name='wp_category_name',
            field=models.CharField(blank=True, default='', editable=False, max_length=150, verbose_name='اسم القسم في ووردبريس'),
        ),
    ]
