# Generated by Django 5.2.14 on 2026-07-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0047_aiimportlog_wp_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='cost_cap_alert_sent_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='تاريخ آخر تنبيه لوصول الحد الأقصى'),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='daily_cost_limit_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='عند وصول إجمالي تكلفة اليوم لهذا الرقم، يتوقف النظام تلقائياً عن أي توليد جديد حتى بداية اليوم التالي، بغض النظر عن السبب - حماية من أي خلل غير متوقع يستهلك الميزانية. اتركه فارغاً لتعطيل هذا الحد.', max_digits=6, null=True, verbose_name='الحد الأقصى اليومي لتكلفة الذكاء الاصطناعي (USD)'),
        ),
    ]
