# Generated by Django 5.2.14 on 2026-06-03 08:46

import taggit.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='auth_key',
            new_name='auth',
        ),
        migrations.RenameField(
            model_name='pushsubscription',
            old_name='p256dh_key',
            new_name='p256dh',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_active',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
