# Generated by Django 5.2.14 on 2026-06-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_auth_key_pushsubscription_auth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Google Analytics Tracking ID (e.g. G-XXXXXXX)', max_length=50, null=True),
        ),
    ]
