# Generated by Django 5.2.15 on 2026-06-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_google_analytics_id'),
        ('news', '0004_article_auto_translate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_description', models.TextField(blank=True, null=True)),
                ('seo_description_ar', models.TextField(blank=True, null=True)),
                ('seo_description_en', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_keywords_en', models.CharField(blank=True, max_length=255, null=True)),
                ('show_breaking_news', models.BooleanField(default=True)),
                ('show_slider', models.BooleanField(default=True)),
                ('show_featured', models.BooleanField(default=True)),
                ('show_popular', models.BooleanField(default=True)),
                ('slider_count', models.PositiveIntegerField(default=5)),
                ('featured_count', models.PositiveIntegerField(default=4)),
                ('popular_count', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('design_style', models.CharField(choices=[('grid', 'شبكة (Grid)'), ('list', 'قائمة (List)')], default='grid', max_length=20)),
                ('article_count', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
