# Generated by Django 5.2.15 on 2026-06-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepagesettings_homepagecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategory',
            name='design_style',
            field=models.CharField(choices=[('featured_grid', 'شبكة رئيسية (Featured Grid)'), ('dark_cards', 'بطاقات داكنة (Dark Cards)'), ('mixed_grid', 'شبكة مختلطة (Mixed Grid)'), ('tall_cards', 'بطاقات طولية (Tall Cards)'), ('simple_cards', 'بطاقات بسيطة (Simple Cards)'), ('country_cards', 'بطاقات دول (Country Cards)'), ('grid', 'شبكة عادية (Grid)'), ('list', 'قائمة جانبية (List)')], default='grid', max_length=20),
        ),
    ]
