# Generated by Django 5.2.15 on 2026-06-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepagecategory_design_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='authors_section_order',
            field=models.PositiveIntegerField(default=2, verbose_name="ترتيب قسم 'أصوات مغاربية' (يظهر بعد أي قسم)"),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_authors_section',
            field=models.BooleanField(default=True, verbose_name="عرض قسم 'أصوات مغاربية'"),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='featured_count',
            field=models.PositiveIntegerField(default=4, verbose_name='عدد الأخبار المميزة'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='popular_count',
            field=models.PositiveIntegerField(default=5, verbose_name='عدد الأخبار الأكثر قراءة'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_breaking_news',
            field=models.BooleanField(default=True, verbose_name='عرض الأخبار العاجلة'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_featured',
            field=models.BooleanField(default=True, verbose_name='عرض الأخبار المميزة'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_popular',
            field=models.BooleanField(default=True, verbose_name='عرض الأخبار الأكثر قراءة'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='show_slider',
            field=models.BooleanField(default=True, verbose_name='عرض معرض الصور'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='slider_count',
            field=models.PositiveIntegerField(default=5, verbose_name='عدد أخبار المعرض'),
        ),
    ]
