# Generated by Django 5.2.15 on 2026-06-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepagesettings_authors_section_order_and_more'),
        ('news', '0004_article_auto_translate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_categories',
            field=models.ManyToManyField(blank=True, related_name='footer_settings', to='news.category', verbose_name='أقسام أسفل الموقع (Footer)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(blank=True, help_text='نبذة تعريفية قصيرة تظهر في أسفل الموقع.', null=True, verbose_name='وصف الفوتر'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط إنستجرام'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='navbar_categories',
            field=models.ManyToManyField(blank=True, related_name='navbar_settings', to='news.category', verbose_name='أقسام القائمة العلوية (Header)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط تويتر / X'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب'),
        ),
    ]
