# Generated by Django 5.2.15 on 2026-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authorexpertise'),
        ('core', '0007_sitesettings_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='authors_section_title',
            field=models.CharField(default='أصوات مغاربية', max_length=255, verbose_name='عنوان قسم الكتاب'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='featured_authors',
            field=models.ManyToManyField(blank=True, to='accounts.authorprofile', verbose_name='الكتاب المختارون'),
        ),
    ]
