# Generated by Django 5.2.15 on 2026-06-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homepagesettings_authors_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategory',
            name='article_count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
