# Generated by Django 5.2.15 on 2026-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_homepagecategory_article_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecategory',
            name='article_count',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
