# Generated by Django 5.2.14 on 2026-06-03 08:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorprofile',
            old_name='biography',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='pen_name',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='authorprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='bio_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='bio_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='display_name_ar',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='email_public',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='role',
            field=models.CharField(choices=[('writer', 'Writer'), ('editor', 'Editor'), ('admin', 'Admin/Chief Editor')], default='writer', max_length=50),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
