# Generated by Django 5.2.14 on 2026-06-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_biography_authorprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='can_delete_articles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='can_edit_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='can_publish_directly',
            field=models.BooleanField(default=False),
        ),
    ]
