# Generated by Django 5.2.15 on 2026-06-03 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_authorprofile_can_delete_articles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان (مثال: التحليل الإقليمي)')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف (مثال: السياسات والشؤون المغاربية)')),
                ('icon', models.CharField(default='star', help_text='أيقونة من Material Symbols', max_length=50, verbose_name='الأيقونة')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertises', to='accounts.authorprofile')),
            ],
        ),
    ]
