# Generated by Django 5.2.15 on 2026-06-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_authorexpertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='role',
            field=models.CharField(choices=[('writer', 'كاتب'), ('editor', 'محرر'), ('admin', 'مدير/رئيس تحرير')], default='writer', max_length=50),
        ),
    ]
