# Generated by Django 5.2.15 on 2026-06-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_authorprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='show_in_team_page',
            field=models.BooleanField(default=True, verbose_name='إظهار في صفحة فريق العمل'),
        ),
    ]
