import re

translation_map = {
    "البحث": "Search",
    "اتصل بنا": "Contact Us",
    "رمز التحقق (CAPTCHA) غير صحيح. يرجى المحاولة مرة أخرى.": "Incorrect CAPTCHA. Please try again.",
    "تم إرسال رسالتكم بنجاح! سنتواصل معكم في أقرب وقت.": "Your message has been sent successfully! We will contact you soon.",
    "تم استلام رسالتكم بنجاح! (نمط التطوير الفعال)": "Your message was received successfully! (Development Mode)",
    "من نحن": "About Us",
    "كل المقالات": "All Articles",
    "الكتاب": "Authors",
    "تم إضافة تعليقك بنجاح!": "Your comment has been added successfully!",
    "لا يمكن إضافة تعليق فارغ.": "Cannot add an empty comment.",
    "تم إزالة الإعجاب بالمقال.": "Unlike article successful.",
    "تم تسجيل إعجابك بالمقال!": "You liked the article!",
    "تم إزالة المقال من المحفوظات.": "Article removed from bookmarks.",
    "تم حفظ المقال في مفضلتك!": "Article saved to bookmarks!",
    "تسجيل الدخول": "Login",
    "مرحباً بك مجدداً. الرجاء إدخال بياناتك للمتابعة.": "Welcome back. Please enter your credentials to continue.",
    "اسم المستخدم أو كلمة المرور غير صحيحة. يرجى المحاولة مرة أخرى.": "Incorrect username or password. Please try again.",
    "اسم المستخدم": "Username",
    "أدخل اسم المستخدم الخاص بك": "Enter your username",
    "كلمة المرور": "Password",
    "دخول": "Login",
    "من نحن | صوت المغرب العربي": "About Us | Voice of Al-Maghrib",
    "رؤيتنا ورسالتنا الصحفية": "Our Vision & Editorial Mission",
    "الموضوعية والاستقلالية": "Objectivity & Independence",
    "العمق الإقليمي": "Regional Depth",
    "حقائق وأرقام": "Facts & Figures",
    "المكاتب الإقليمية": "Regional Offices",
    "محرر ومراسل في الميدان": "editor and reporter in the field",
    "معدل القراءات الشهري": "Monthly Readership Rate",
    "تواصلوا مع صوت المغرب العربي": "Contact Voice of Al-Maghrib",
    "راسلنا مباشرة": "Message Us Directly",
    "الاسم الكامل": "Full Name",
    "أدخل اسمك": "Enter your name",
    "البريد الإلكتروني": "Email Address",
    "الموضوع": "Subject",
    "قسم التحرير": "Editorial Department",
    "الدعم التقني": "Technical Support",
    "الإعلان والتسويق": "Advertising & Marketing",
    "اقتراحات عامة": "General Suggestions",
    "رمز التحقق (CAPTCHA)": "CAPTCHA Verification",
    "أدخل ناتج العملية الحسابية": "Enter the result of the equation",
    "إرسال الرسالة": "Send Message",
    "عرض خريطة المكاتب": "Show Office Map",
    "قنوات الاتصال": "Communication Channels",
    "التحرير": "Editorial",
    "الإعلانات": "Advertising",
    "الهاتف الدولي": "International Phone",
    "تابعونا على": "Follow us on",
    "حضورنا الميداني": "Our Field Presence",
    "مكاتبنا الإقليمية": "Our Regional Offices",
    "الدار البيضاء": "Casablanca",
    "المقر الرئيسي": "Headquarters",
    "شارع الجيش الملكي، برج الأحباس، الدار البيضاء، المغرب": "Faraj Army Street, Al Habas Tower, Casablanca, Morocco",
    "اتصل بالمكتب": "Contact Office",
    "الجزائر": "Algiers",
    "مكتب إقليمي": "Regional Office",
    "نهج العقيد عميروش، وسط المدينة، الجزائر العاصمة": "Colonel Amirouche St, Downtown, Algiers",
    "تونس": "Tunis",
    "شارع الحبيب بورقيبة، تونس العاصمة، تونس": "Habib Bourguiba Avenue, Tunis, Tunisia",
    "طرابلس": "Tripoli",
    "ميدان الجزائر، مجمع المكاتب، طرابلس، ليبيا": "Algeria Square, Office Complex, Tripoli, Libya",
    "نواكشوط": "Nouakchott",
    "شارع جمال عبد الناصر، تفرغ زينة، نواكشوط": "Gamal Abdel Nasser Street, Tevragh Zeina, Nouakchott",
    "الرئيسية": "Home",
    "إقرأ المزيد": "Read More",
    "المزيد": "More",
    "عرض الكل": "View All",
    "عرض المزيد": "View More",
    "استكشف": "Explore",
    "نخبة من المفكرين والكتاب يحللون الواقع المغاربي": "A selection of thinkers and writers analyzing the Maghreb reality",
    "نتائج البحث": "Search Results",
    "نتائج البحث عن": "Search results for",
    "تم العثور على %(count)s نتيجة تطابق كلمات البحث.": "Found %(count)s matching results.",
    "دقائق": "minutes",
    "السابق": "Previous",
    "التالي": "Next",
    "لم نجد أي نتائج للمقالات": "No articles found",
    "تصفح آخر الأخبار": "Browse latest news",
    "بحث جديد": "New Search",
    "ابحث عن أخبار...": "Search for news...",
    "ابحث الآن": "Search Now",
    "تعديل مقال": "Edit Article",
    "إضافة مقال جديد": "Add New Article",
    "تحديث محتوى المقال الحالي وإعدادات النشر": "Update current article content and publishing settings",
    "اكتب مقالاً جديداً وقم بتعبئة بيانات اللغتين العربية والإنجليزية": "Write a new article and fill in both Arabic and English fields",
    "الترجمة التلقائية للإنجليزية": "Auto-translate to English",
    "محتوى المقال الرئيسي (عربي وإنجليزي)": "Main Article Content (Arabic & English)",
    "الرابط الفرعي (Slug)": "Slug URL",
    "اتركه فارغاً ليتم إنشاؤه تلقائياً من العنوان": "Leave empty to generate automatically from title",
    "القسم الأساسي": "Primary Category",
    "إعدادات النشر والوسائط": "Publishing & Media Settings",
    "حالة النشر": "Publishing Status",
    "الوسوم (مفصولة بفاصلة)": "Tags (separated by comma)",
    "مثال: سياسة, اقتصاد, عاجل": "e.g. politics, economy, breaking",
    "خيارات إضافية": "Additional Options",
    "مقال مميز (Featured)": "Featured Article",
    "خبر عاجل (Breaking)": "Breaking News",
    "السماح بالتعليقات": "Allow Comments",
    "صورة الغلاف": "Cover Image",
    "الصورة الحالية": "Current Image",
    "المقتطف والمحتوى الكامل": "Excerpt & Full Content",
    "إعدادات محركات البحث (SEO)": "Search Engine Optimization (SEO) Settings",
    "حفظ التغييرات": "Save Changes",
    "إلغاء وتراجع": "Cancel and Go Back",
    "معاينة المقال": "Preview Article",
    "معاينة مباشرة للمقال": "Live Article Preview",
    "استعرض كيف سيظهر المقال للقراء باللغتين العربية والإنجليزية": "See how the article will appear to readers in both Arabic and English",
    "تعديل هذا المقال": "Edit This Article",
    "العودة للقائمة": "Back to List",
    "حالة المقال": "Article Status",
    "منشور": "Published",
    "مسودة": "Draft",
    "مراجعة": "Review",
    "مؤرشف": "Archived",
    "الكاتب": "Author",
    "القسم": "Category",
    "المشاهدات": "Views",
    "وقت القراءة": "Read Time",
    "تاريخ النشر": "Publish Date",
    "المسودة العربية": "Arabic Draft",
    "English Draft": "English Draft",
    "بيانات السيو (RTL SEO)": "SEO Metadata (RTL)",
    "عنوان SEO:": "SEO Title:",
    "وصف SEO:": "SEO Description:",
    "إدارة المقالات": "Manage Articles",
    "تصفية وتعديل وإجراء عمليات جماعية على المقالات": "Filter, edit, and perform bulk operations on articles",
    "قائمة المقالات": "Articles List",
    "ابحث في العنوان أو المحتوى...": "Search in title or content...",
    "كل الأقسام": "All Categories",
    "كل الحالات": "All Statuses",
    "تصفية": "Filter",
    "إعادة تعيين": "Reset",
    "العمليات الجماعية للمقالات المحددة:": "Bulk operations on selected articles:",
    "اختر الإجراء...": "Choose action...",
    "نشر": "Publish",
    "تحويل إلى مسودة": "Convert to Draft",
    "إرسال للمراجعة": "Send for Review",
    "أرشفة": "Archive",
    "حذف مؤقت (سلة المحذوفات)": "Soft Delete (Trash)",
    "تطبيق الإجراء": "Apply Action",
    "مجموع المقالات المعروضة": "Total Articles Displayed",
    "المقال": "Article",
    "الحالة": "Status",
    "تاريخ الإنشاء": "Creation Date",
    "العمليات": "Operations",
    "تعديل": "Edit",
    "معاينة مباشرة": "Live Preview",
    "لا يوجد مقالات تطابق خيارات التصفية الحالية.": "No articles match the current filter options.",
    "الصفحة": "Page",
    "من": "of",
    "تسجيل كاتب جديد": "Register New Author",
    "قم بإنشاء حساب مستخدم جديد ككاتب أو محرر وعيّن صلاحياته الفردية مباشرة": "Create a new user account as author or editor and set individual permissions directly",
    "بيانات الحساب وتسجيل الدخول": "Account & Login Information",
    "الملف التعريفي للكاتب (Public Profile)": "Public Author Profile",
    "الاسم الذي يظهر للقراء في المقالات": "Display name shown to readers",
    "إعدادات الدور والصلاحيات": "Role & Permissions Settings",
    "تحديد صلاحيات الكاتب الإضافية": "Specify Additional Author Permissions",
    "إلغاء": "Cancel",
    "إدارة الكاتب": "Author Management",
    "إدارة صلاحيات وبيانات الكاتب": "Manage Author Permissions & Info",
    "تحرير الصلاحيات المخصصة واستعراض أداء مقالات الكاتب": "Edit custom permissions and review author's article performance",
    "العودة لقائمة الكتاب": "Back to Authors List",
    "الصفحة العامة للكاتب": "Public Author Page",
    "المقالات المكتوبة": "Written Articles",
    "مشاهدات المقالات": "Article Views",
    "مقالات الكاتب": "Author's Articles",
    "البحث في مقالات الكاتب...": "Search in author's articles...",
    "معاينة": "Preview",
    "لا يوجد مقالات مكتوبة مطابقة للبحث.": "No written articles match the search.",
    "البيانات والصلاحيات": "Data & Permissions",
    "مجالات التغطية والخبرة (المعروضة للجمهور)": "Coverage Areas & Expertise (Publicly Displayed)",
    "العنوان": "Title",
    "الوصف": "Description",
    "الأيقونة": "Icon",
    "حذف هذا المجال": "Delete this area",
    "تحديث الإعدادات والصلاحيات": "Update Settings & Permissions",
    "إحصائيات الكاتب": "Author Statistics",
    "استعرض تفاصيل ملفك المهني وإحصائيات قراءة مقالاتك": "Review your professional profile details and article reading statistics",
    "التخصص": "Specialization",
    "إجمالي المقالات المكتوبة": "Total Written Articles",
    "تتضمن المقالات المنشورة والمسودات والأرشيف": "Includes published, draft, and archived articles",
    "إجمالي مشاهدات مقالاتك": "Total views of your articles",
    "متوسط القراءات لكل مقال": "Average views per article",
    "تاريخ الانضمام للفريق": "Date Joined Team",
    "مقالاتك الأخيرة": "Your Recent Articles",
    "لم تقم بكتابة أي مقالات بعد.": "You haven't written any articles yet.",
    "إدارة كتّاب الموقع": "Manage Site Authors",
    "استعرض إحصائيات الكتاب، الأدوار، والصلاحيات المخصصة لكل كاتب": "Review author stats, roles, and custom permissions assigned to each author",
    "قائمة الكتّاب المسجلين": "Registered Authors List",
    "إضافة كاتب جديد": "Add New Author",
    "إجمالي الكتاب": "Total Authors",
    "الدور": "Role",
    "عدد المقالات": "Articles Count",
    "إجمالي المشاهدات": "Total Views",
    "الصلاحيات الممنوحة": "Granted Permissions",
    "تاريخ الانضمام": "Joined Date",
    "نشط": "Active",
    "معطل": "Disabled",
    "نشر مباشر بدون مراجعة": "Direct publishing without review",
    "نشر مباشر": "Direct Publish",
    "تعديل مقالات الكتاب الآخرين": "Edit other authors' articles",
    "تعديل للغير": "Edit Others",
    "حذف المقالات": "Delete Articles",
    "حذف": "Delete",
    "صلاحيات قياسية": "Standard Permissions",
    "إدارة": "Manage",
    "عرض الصفحة العامة للكاتب": "View public author page",
    "لا يوجد كتاب مسجلين حالياً.": "No registered authors found.",
    "لوحة التحكم": "Dashboard",
    "المقالات": "Articles",
    "الأقسام": "Categories",
    "إعدادات الرئيسية": "Homepage Settings",
    "إعدادات الموقع العامة": "General Site Settings",
    "إدارة الكتاب": "Manage Authors",
    "زيارة الموقع": "Visit Site",
    "تسجيل الخروج": "Logout",
    "مرحباً بك": "Welcome",
    "هذه هي لوحة التحكم المخصصة لإدارة المحتوى": "This is the content management dashboard",
    "مدير الموقع": "Site Administrator",
    "محرر": "Editor",
    "كاتب": "Author",
    "الأقسام والتصنيفات": "Categories & Classifications",
    "استعرض شجرة تصنيفات المقالات المتاحة في النظام": "Browse the article categories tree available in the system",
    "شجرة الأقسام": "Categories Tree",
    "إضافة قسم جديد": "Add New Category",
    "إجمالي الأقسام": "Total Categories",
    "تعديل القسم": "Edit Category",
    "القسم الأب": "Parent Category",
    "رئيسي": "Main",
    "ترتيب العرض": "Display Order",
    "لا يوجد أقسام مسجلة في النظام حالياً.": "No categories registered in the system currently.",
    "تحديث بيانات القسم الحالي وإعدادات الأرشفة والترتيب": "Update current category info, archiving, and order settings",
    "قم بإنشاء قسم مقالات جديد وتعبئة البيانات باللغتين العربية والإنجليزية": "Create a new article category and fill in data in both Arabic and English",
    "معلومات القسم الأساسية (عربي وإنجليزي)": "Category Basic Info (Arabic & English)",
    "اتركه فارغاً ليتم توليده تلقائياً من الاسم": "Leave empty to generate automatically from name",
    "إعدادات المظهر والترتيب": "Appearance & Ordering Settings",
    "اسم الأيقونة من Material Symbols مثل (folder, article, book)": "Icon name from Material Symbols e.g. (folder, article, book)",
    "رمز اللون بالصيغة الست عشرية (مثال: #3b82f6)": "Hex color code (e.g. #3b82f6)",
    "حفظ القسم": "Save Category",
    "لوحة القيادة والتحكم": "Control & Dashboard Panel",
    "نظرة عامة على أداء المحتوى والنشاطات الأخيرة": "Overview of content performance and recent activities",
    "الزوار الفريدين (تقديري)": "Unique Visitors (Estimated)",
    "معدل تفاعل الزوار اليومي": "Daily Visitor Engagement Rate",
    "إجمالي مشاهدات المقالات": "Total Article Views",
    "مقارنة بالشهر الماضي": "Compared to last month",
    "المقالات الجديدة": "New Articles",
    "اليوم": "Today",
    "هذا الأسبوع": "This Week",
    "التعليقات": "Comments",
    "تفاعل القراء مع منشوراتك": "Readers' interaction with your posts",
    "معدل نشر المقالات (آخر 7 أيام)": "Articles publishing rate (last 7 days)",
    "توزيع المقالات حسب الأقسام": "Articles distribution by categories",
    "المقالات الأكثر قراءة": "Most Read Articles",
    "لا يوجد مقالات معروضة حالياً.": "No articles currently displayed.",
    "التعليقات المعلقة بانتظار المراجعة": "Pending Comments Awaiting Review",
    "على": "on",
    "موافقة": "Approve",
    "كل التعليقات تمت مراجعتها والموافقة عليها!": "All comments have been reviewed and approved!",
    "سجل النشاطات الأخيرة": "Recent Activity Log",
    "العملية بواسطة": "Operation by",
    "لا يوجد نشاطات مسجلة.": "No registered activities.",
    "المقالات المنشورة": "Published Articles",
    "إعدادات الصفحة الرئيسية": "Homepage Settings",
    "الأقسام الرئيسية (العلوية والجانبية)": "Main Categories (Header & Footer)",
    "إظهار/إخفاء": "Show/Hide",
    "الإعدادات الرقمية": "Numerical Settings",
    "الأقسام الإخبارية (في وسط الصفحة)": "News Sections (Center of Page)",
    "إعدادات الموقع العامة (الهيدر والفوتر)": "General Site Settings (Header & Footer)",
    "المعلومات الأساسية": "Basic Information",
    "إعدادات القائمة العلوية (Navbar)": "Header Menu Settings (Navbar)",
    "إعدادات الفوتر (Footer)": "Footer Settings",
    "اشترك في نشرتنا الإخبارية": "Subscribe to our newsletter",
    "اشترك الآن": "Subscribe Now",
    "عن المؤسسة": "About the Institution",
    "الميثاق التحريري": "Editorial Charter",
    "فريق العمل": "Editorial Team",
    "سياسة إقليمية": "Regional Politics",
    "توجهات اقتصادية": "Economic Trends",
    "تراث وثقافة": "Heritage & Culture",
    "الساحة الرياضية": "Sports Arena",
    "قانوني": "Legal",
    "سياسة الخصوصية": "Privacy Policy",
    "شروط الاستخدام": "Terms of Use",
    "الأرشيف": "Archive",
    "Premium Journalism.": "Premium Journalism.",
    "السياسة": "Politics",
    "الاقتصاد": "Economy",
    "الثقافة": "Culture",
    "الرياضة": "Sports",
    "عاجل": "Breaking",
    "دقائق قراءة": "minutes read",
    "مشاركة": "Share",
    "حفظ": "Save",
    "إعجاب": "Like",
    "أضف تعليقاً": "Add a Comment",
    "اكتب تعليقك هنا...": "Write your comment here...",
    "إرسال التعليق": "Submit Comment",
    "يرجى تسجيل الدخول لتتمكن من التعليق على المقال.": "Please login to be able to comment on the article.",
    "رد": "Reply",
    "اكتب ردك هنا...": "Write your reply here...",
    "إرسال الرد": "Submit Reply",
    "كن أول من يعلق على هذا المقال.": "Be the first to comment on this article.",
    "مقالات ذات صلة": "Related Articles",
    "لا يوجد مقالات ذات صلة": "No related articles found",
    "النشرة البريدية": "Newsletter",
    "احصل على أهم الأخبار مباشرة في بريدك.": "Get the most important news directly in your inbox.",
    "اقرأ أيضاً": "Read Also",
    "تم نسخ الرابط بنجاح!": "Link copied successfully!",
    "كل الأخبار والمقالات": "All News & Articles",
    "كل المقالات والأخبار": "All Articles & News",
    "لا يوجد مقالات منشورة حالياً": "No articles published currently",
    "النشرة الإخبارية": "Newsletter",
    "اشترك لتصلك آخر التحليلات والأخبار العاجلة مباشرة في بريدك الإلكتروني.": "Subscribe to receive the latest analysis and breaking news directly in your email.",
    "اشتراك الآن": "Subscribe Now",
    "صفحة الكاتب": "Author's Page",
    "ابحث في مقالات الكاتب...": "Search in author's articles...",
    "مقال": "Article",
    "لا يوجد مقالات منشورة تطابق بحثك حالياً": "No published articles match your search currently",
    "قسم": "Category",
    "الأقسام الفرعية": "Subcategories",
    "ترتيب حسب": "Sort By",
    "الأحدث": "Latest",
    "الأكثر قراءة": "Most Read",
    "لا يوجد مقالات في هذا القسم حالياً": "No articles in this category currently",
    "اشترك لتصلك آخر التحليلات والأخبار العاجلة في هذا القسم.": "Subscribe to receive the latest analysis and breaking news in this category.",
    "الأرشيف الصحفي": "Press Archive",
    "الأرشيف الإخباري": "News Archive",
    "تصفح كافة المقالات والتقارير والتحليلات التي تم نشرها في الموقع مرتبة ومصنفة بحسب تاريخ النشر.": "Browse all articles, reports, and analyses published on the website sorted and classified by publication date.",
    "تصفية الأرشيف لـ:": "Filter archive for:",
    "إلغاء التصفية": "Clear filter",
    "لا يوجد مقالات في هذا الأرشيف للفترة المحددة.": "No articles found in this archive for the specified period.",
    "تصفح حسب الشهر": "Browse by Month",
    "لا يوجد تاريخ أرشفة متاح حالياً.": "No archive history available currently.",
    "معاييرنا الأخلاقية والمهنية": "Our Ethical & Professional Standards",
    "الصحافة مسؤولية وأمانة. نلتزم بأعلى المعايير المهنية لضمان تقديم محتوى موثوق ودقيق لجمهورنا.": "Journalism is a responsibility and a trust. We adhere to the highest professional standards to ensure providing reliable and accurate content to our audience.",
    "مبادئ العمل الصحفي لدينا": "Our Principles of Journalistic Work",
    "يمثل هذا الميثاق العهد المهني والأخلاقي الذي يلتزم به كافة الصحفيين والكتّاب والمحررين العاملين في منصتنا الإعلامية. نحن نؤمن بأن ثقة القارئ هي رأسمالنا الأكبر، ولذلك نعمل جاهدين لصونها والحفاظ عليها من خلال اتباع المعايير التحريرية الصارمة التالية.": "This charter represents the professional and ethical pledge that all journalists, writers, and editors working in our media platform commit to. We believe that the reader's trust is our greatest asset, and therefore we work hard to preserve and maintain it by following these strict editorial standards.",
    "الدقة والتحقق من المعلومات": "Accuracy & Verification of Information",
    "نسعى جاهدين لنقل الأخبار بدقة تامة. نلتزم بالتحقق من صحة المعلومات من مصادر متعددة وموثوقة قبل النشر، مع الفصل التام بين الخبر والتحليل أو الرأي الشخصي.": "We strive to report news with absolute accuracy. We commit to verifying the authenticity of information from multiple reliable sources before publication, while completely separating news from analysis or personal opinion.",
    "الموضوعية والحياد والتوازن": "Objectivity, Neutrality & Balance",
    "نلتزم بعرض مختلف وجهات النظر بتوازن وموضوعية ودون تحيز. لا نسمح للميول الشخصية أو السياسية أو الفكرية بالتأثير على تغطيتنا الصحفية وصياغة الأخبار.": "We commit to presenting various viewpoints with balance, objectivity, and without bias. We do not allow personal, political, or intellectual leanings to influence our journalistic coverage and news writing.",
    "حماية المصادر والسرية": "Protection of Sources & Confidentiality",
    "نحترم رغبة المصادر في عدم الكشف عن هويتها متى ما تطلب الأمر ذلك لحمايتها، ونلتزم بالسرية المهنية المطلقة وحماية سرية اتصالاتنا وتوثيقاتنا الصحفية.": "We respect the desire of sources to remain anonymous whenever needed for their protection, and we commit to absolute professional confidentiality and the protection of the confidentiality of our communications and journalistic documentation.",
    "المسؤولية الاجتماعية والأخلاقية": "Social & Ethical Responsibility",
    "نتجنب نشر ما يحرض على الكراهية، العنف، العنصرية، أو التمييز بكافة أشكاله. نحترم الخصوصية الفردية ونراعي القيم الإنسانية والقوانين المعمول بها.": "We avoid publishing anything that incites hatred, violence, racism, or discrimination in all its forms. We respect individual privacy and consider human values and applicable laws.",
    "سياسة التصحيح والاعتذار": "Correction & Apology Policy",
    "المصداقية تتطلب الشجاعة في الاعتراف بالخطأ. إذا تبين لنا وجود خطأ غير مقصود في أي خبر أو تقرير منشور، فإننا نلتزم بتصحيحه وتحديث المادة الصحفية فوراً وبكل شفافية، مع الإشارة إلى أن المادة قد تم تعديلها لتصحيح الخطأ الوارد.": "Credibility requires the courage to admit error. If it becomes clear to us that there is an unintended error in any published news or report, we commit to correcting it and updating the journalistic material immediately and with full transparency, noting that the material has been modified to correct the error.",
    "للإبلاغ عن الأخطاء التحريرية أو طلب التصحيح:": "To report editorial errors or request corrections:",
    "فروعنا ومكاتبنا الإقليمية": "Our Branches & Regional Offices",
    "شبكة مكاتبنا وصحفيينا تغطي مختلف دول المغرب العربي والشرق الأوسط لتزويدكم بالخبر فور حدوثه.": "Our network of offices and journalists covers various countries of the Arab Maghrib and the Middle East to provide you with news as it happens.",
    "شارع الحبيب بورقيبة، عمارة المغرب العربي، تونس العاصمة": "Habib Bourguiba Avenue, Arab Maghrib Building, Tunis",
    "شارع محمد الخامس، برج الأعمال، الرباط": "Mohamed V Avenue, Business Tower, Rabat",
    "حي حيدرة، عمارة الصنوبر، الجزائر العاصمة": "Hydra District, Pine Building, Algiers",
    "شارع التحرير، الدقي، الجيزة، القاهرة الكبرى": "El-Tahrir Street, Dokki, Giza, Greater Cairo",
    "مدينة دبي للإعلام، مبنى رقم 4، دبي، الإمارات العربية المتحدة": "Dubai Media City, Building No. 4, Dubai, United Arab Emirates",
    "هل ترغب في التواصل مع التحرير مباشرة؟": "Do you wish to contact editorial directly?",
    "إذا كان لديك خبر، مقترح، أو ترغب في إرسال بيان صحفي، يمكنك استخدام نموذج الاتصال المباشر لإيصال رسالتك إلى قسم التحرير المعني مباشرة.": "If you have news, a proposal, or wish to send a press release, you can use the direct contact form to deliver your message directly to the relevant editorial department.",
    "اذهب لنموذج الاتصال بنا": "Go to Contact Us Form",
    "خصوصيتك تهمنا. نوضح هنا كيفية جمعنا لبياناتك وحمايتها واستخدامها عند تصفح موقعنا.": "Your privacy is important to us. Here we clarify how we collect, protect, and use your data when browsing our website.",
    "مقدمة عامة": "General Introduction",
    "نحن نلتزم بحماية سرية وخصوصية بيانات المستخدمين والزوار على موقعنا. توضح هذه السياسة طبيعة المعلومات الشخصية التي نجمعها، وكيفية استخدامها وحمايتها، وحقوقك المتعلقة ببياناتك.": "We are committed to protecting the confidentiality and privacy of users and visitors data on our website. This policy explains the nature of the personal information we collect, how we use and protect it, and your rights regarding your data.",
    "قد نقوم بجمع الأنواع التالية من المعلومات عند استخدامك لموقعنا:": "We may collect the following types of information when you use our website:",
    "المعلومات الشخصية التي تقدمها طواعية عند الاشتراك في النشرة البريدية أو استخدام نموذج الاتصال (مثل الاسم والبريد الإلكتروني).": "Personal information you provide voluntarily when subscribing to the newsletter or using the contact form (such as name and email).",
    "بيانات التصفح والاستخدام، وتشمل عنوان البروتوكول (IP)، نوع المتصفح، الصفحات التي زرتها، ووقت الزيارة.": "Browsing and usage data, including IP address, browser type, pages visited, and visit time.",
    "ملفات تعريف الارتباط (Cookies) لتحسين تجربة المستخدم وتحليل أداء الموقع وإظهار الإعلانات المناسبة.": "Cookies to improve user experience, analyze site performance, and show suitable advertisements.",
    "نستخدم البيانات التي نجمعها للأغراض التالية:": "We use the data we collect for the following purposes:",
    "الرد على استفساراتك ورسائلك التي ترسلها لنا عبر نموذج الاتصال.": "Responding to your inquiries and messages sent via the contact form.",
    "تحليل حركة المرور وسلوك الزوار لتحسين وتطوير أداء الموقع وسرعته.": "Analyzing traffic and visitor behavior to improve and develop site performance and speed.",
    "نحن نطبق إجراءات أمنية تقنية وإدارية صارمة لمنع الوصول غير المصرح به إلى بياناتك أو تعديلها أو كشفها. نؤكد أننا لا نقوم ببيع أو تأجير أو مشاركة معلوماتك الشخصية مع أطراف ثالثة لأغراض تجارية، باستثناء الحالات التي يتطلبها القانون أو لحماية حقوقنا القانونية.": "We apply strict technical and administrative security measures to prevent unauthorized access, modification, or disclosure of your data. We confirm that we do not sell, rent, or share your personal information with third parties for commercial purposes, except as required by law or to protect our legal rights.",
    "لك الحق في الوصول إلى بياناتك الشخصية التي نحتفظ بها، أو طلب تصحيحها أو تعديلها، كما يمكنك في أي وقت إلغاء الاشتراك من النشرة البريدية عبر رابط إلغاء الاشتراك المتوفر في نهاية كل رسالة بريدية نرسلها إليك.": "You have the right to access your personal data that we hold, or request its correction or modification. You can also unsubscribe from the newsletter at any time via the unsubscribe link provided at the end of every email we send you.",
    "التعديلات على سياسة الخصوصية": "Amendments to Privacy Policy",
    "نحتفظ بالحق في تعديل أو تحديث سياسة الخصوصية هذه في أي وقت. سيتم نشر أي تغييرات هنا مع تحديث تاريخ آخر تعديل في أسفل الصفحة. ننصح بمراجعة هذه الصفحة بشكل دوري للوقوف على أي مستجدات.": "We reserve the right to modify or update this privacy policy at any time. Any changes will be posted here with the date of the last update at the bottom of the page. We advise you to review this page periodically to keep abreast of any updates.",
    "يرجى قراءة شروط الاستخدام بعناية قبل تصفح الموقع أو استخدام أي من خدماته الإخبارية.": "Please read the terms of use carefully before browsing the website or using any of its news services.",
    "دخولك وتصفحك لموقع المغرب العربي يعني موافقتك الكاملة واللامشروطة على الالتزام بجميع شروط الاستخدام المذكورة هنا، والامتثال لكافة القوانين واللوائح المعمول بها محلياً ودولياً. إذا كنت لا توافق على هذه الشروط، يرجى التوقف عن استخدام الموقع.": "Your entry and browsing of the Al-Maghrib website means your full and unconditional agreement to abide by all the terms of use mentioned here, and to comply with all applicable local and international laws and regulations. If you do not agree to these terms, please stop using the website.",
    "جميع المحتويات المنشورة على الموقع، بما في ذلك الأخبار، المقالات، التحليلات، الصور، الفيديوهات، الشعارات، والتصميمات، هي ملكية فكرية حصرية لموقع المغرب العربي أو شركائه من وكالات الأنباء، وهي محمية بموجب قوانين الملكية الفكرية وحقوق النشر الدولية.": "All content published on the website, including news, articles, analyses, images, videos, logos, and designs, is the exclusive intellectual property of the Al-Maghrib website or its news agency partners, and is protected under international intellectual property and copyright laws.",
    "لا يُسمح بنسخ أو إعادة إنتاج أو نشر أو توزيع أي جزء من محتوى الموقع دون الحصول على إذن كتابي مسبق من إدارة الموقع، مع وجوب ذكر المصدر بوضوح ووضع رابط مباشر للمادة الأصلية عند الاقتباس المصرح به.": "Copying, reproducing, publishing, or distributing any part of the website content is not allowed without obtaining prior written permission from the website administration, and the source must be clearly mentioned with a direct link to the original material in case of authorized citation.",
    "عند استخدامك للموقع، فإنك تلتزم بعدم:": "When using the website, you commit not to:",
    "استخدام الموقع بأي طريقة تؤدي إلى إلحاق الضرر به أو تعطيل خوادمه أو شبكاته المتصلة.": "Use the website in any way that causes damage to it or disrupts its servers or connected networks.",
    "نشر أو إرسال أي محتوى يحتوي على برمجيات خبيثة أو فيروسات تهدف إلى إتلاف أو اختراق الموقع.": "Publish or transmit any content containing malicious software or viruses aimed at damaging or hacking the website.",
    "استخدام أدوات آلية أو برمجيات كشط البيانات (Scraping) لجمع محتويات الموقع دون إذن مسبق.": "Use automated tools or data scraping software to collect the website's contents without prior permission.",
    "استخدام الموقع للترويج لإعلانات تجارية غير مصرح بها أو إرسال رسائل غير مرغوب فيها (Spam).": "Use the website to promote unauthorized commercial advertisements or send unsolicited messages (Spam).",
    "يتم تقديم المحتوى الإخباري والمعلوماتي على هذا الموقع كما هو، للتعريف العام والتثقيف. على الرغم من بذلنا كافة الجهود لضمان صحة ودقة المعلومات، فإن الموقع لا يضمن خلو المحتوى تماماً من الأخطاء المطبعية أو الفنية غير المقصودة، ولا يتحمل أي مسؤولية عن القرارات التي يتخذها المستخدم بناءً على هذا المحتوى.": "The news and informational content on this website is provided as is, for general information and education. Although we make all efforts to ensure the correctness and accuracy of the information, the website does not guarantee that the content is completely free of unintended typographical or technical errors, and bears no responsibility for decisions made by the user based on this content.",
    "قد يحتوي موقعنا على روابط لمواقع إلكترونية خارجية تديرها أطراف أخرى. هذه الروابط متوفرة لسهولة وصولك فقط، ولا تعني مصادقتنا على محتوياتها أو تحملنا لأي مسؤولية عن ممارسات الخصوصية أو شروط الاستخدام الخاصة بتلك المواقع.": "Our website may contain links to external websites operated by other parties. These links are provided for your convenience only, and do not imply our endorsement of their content or any responsibility on our part for the privacy practices or terms of use of those websites.",
    "تخضع شروط الاستخدام هذه وتفسر وفقاً للقوانين المعمول بها. ويخضع أي نزاع قد ينشأ عن استخدام هذا الموقع للاختصاص الحصري للمحاكم المختصة.": "These terms of use are governed by and construed in accordance with applicable laws. Any dispute arising from the use of this website shall be subject to the exclusive jurisdiction of the competent courts.",
    "البيانات التي نجمعها": "Data We Collect",
    "كيفية استخدام بياناتك": "How We Use Your Data",
    "حماية البيانات ومشاركتها": "Data Protection & Sharing",
    "حقوق المستخدم": "User Rights",
    "الموافقة على الشروط": "Agreement to Terms",
    "حقوق الملكية الفكرية": "Intellectual Property Rights",
    "الاستخدام المقبول": "Acceptable Use",
    "روابط الأطراف الثالثة": "Third-Party Links",
    "القانون الواجب التطبيق": "Applicable Law",
    "ابحث عن...": "Search...",
}

po_file_path = 'locale/en/LC_MESSAGES/django.po'

with open(po_file_path, 'r', encoding='utf-8') as f:
    po_content = f.read()

# We need to replace empty msgstr for msgids that exist in our map.
# We parse the file entry by entry. An entry starts with msgid and is followed by msgstr.
# We can use regex to find msgid/msgstr blocks.
pattern = r'(msgid\s+"([^"]+)"\s*\nmsgstr\s+")([^"]*)(")'

def repl(match):
    prefix = match.group(1)
    msgid = match.group(2)
    msgstr = match.group(3)
    suffix = match.group(4)
    
    if not msgstr and msgid in translation_map:
        return f'{prefix}{translation_map[msgid]}{suffix}'
    return match.group(0)

new_content = re.sub(pattern, repl, po_content)

with open(po_file_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Translation mapping completed!")
